# Generated by Django 3.2 on 2021-07-29 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bestCity',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('city_score', models.IntegerField()),
            ],
            options={
                'verbose_name': '百强城市',
                'db_table': 'bestCity',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '科目',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('collegeID', models.IntegerField(primary_key=True, serialize=False)),
                ('collegeName', models.TextField()),
                ('project985', models.BooleanField(default=False)),
                ('project211', models.BooleanField()),
                ('top', models.BooleanField()),
            ],
            options={
                'verbose_name': '大学',
                'db_table': 'Colleges',
            },
        ),
        migrations.CreateModel(
            name='Firstlevel',
            fields=[
                ('firstlevelID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstlevelName', models.TextField()),
                ('subjectID', models.IntegerField()),
                ('subjectName', models.TextField()),
            ],
            options={
                'verbose_name': '一级学科',
                'db_table': 'Firstlevel',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('provinceID', models.IntegerField(primary_key=True, serialize=False)),
                ('provinceName', models.TextField()),
            ],
            options={
                'verbose_name': '省份',
                'db_table': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='total2020',
            fields=[
                ('total_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_majorName', models.TextField()),
                ('total_year', models.IntegerField()),
                ('total_minScore', models.IntegerField()),
                ('total_categoryID_id', models.IntegerField()),
                ('total_collegeID_id', models.IntegerField()),
                ('total_c1', models.TextField()),
                ('total_c2', models.TextField()),
                ('total_college_loca', models.TextField()),
            ],
            options={
                'verbose_name': '汇总2020',
                'db_table': 'total2020',
            },
        ),
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.category')),
                ('provinceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.provinces')),
            ],
            options={
                'verbose_name': '排名',
                'db_table': 'Rankings',
            },
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majorName', models.TextField()),
                ('year', models.IntegerField()),
                ('minScore', models.IntegerField()),
                ('avgScore', models.IntegerField(null=True)),
                ('maxScore', models.IntegerField(null=True)),
                ('firstlevelIDs', models.TextField(null=True)),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.category')),
                ('collegeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.colleges')),
                ('provinceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.provinces')),
            ],
            options={
                'verbose_name': '专业',
                'db_table': 'Majors',
            },
        ),
        migrations.AddField(
            model_name='colleges',
            name='provinceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.provinces'),
        ),
    ]
